apiVersion: apps/v1
kind: Deployment
metadata:
  name:  personnel office
  labels:
    app:  personnel office
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  personnel office
  template:
    metadata:
      labels:
        app:  personnel office
    spec:
      containers:
        - name:  personnel office
          image: "username/ personnel office:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
