apiVersion: apps/v1
kind: Deployment
metadata:
  name: innovation strategy department
  labels:
    app: innovation strategy department
spec:
  replicas: 1
  selector:
    matchLabels:
      app: innovation strategy department
  template:
    metadata:
      labels:
        app: innovation strategy department
    spec:
      containers:
        - name: innovation strategy department
          image: "username/innovation strategy department:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
