---

apiVersion: apps/v1
kind: Deployment
metadata:
  name:  all departments
  labels:
    app:  all departments
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  all departments
  template:
    metadata:
      labels:
        app:  all departments
    spec:
      containers:
        - name:  all departments
          image: username/ all departments:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: innovation strategy department
  labels:
    app: innovation strategy department
spec:
  replicas: 1
  selector:
    matchLabels:
      app: innovation strategy department
  template:
    metadata:
      labels:
        app: innovation strategy department
    spec:
      containers:
        - name: innovation strategy department
          image: username/innovation strategy department:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name:  personnel office
  labels:
    app:  personnel office
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  personnel office
  template:
    metadata:
      labels:
        app:  personnel office
    spec:
      containers:
        - name:  personnel office
          image: username/ personnel office:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name:  all departments
  labels:
    app:  all departments
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app:  all departments


---


apiVersion: v1
kind: Service
metadata:
  name: innovation strategy department
  labels:
    app: innovation strategy department
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: innovation strategy department


---


apiVersion: v1
kind: Service
metadata:
  name:  personnel office
  labels:
    app:  personnel office
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app:  personnel office

